const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const {JSDOM}=require(process.env.CODEX_NODE_MODULES?process.env.CODEX_NODE_MODULES+'/jsdom':'jsdom');
test('library filters, replacements survive reload and recorded original sets survive finish/edit',()=>{
  let dom=boot(),w=dom.window,d=w.document;
  d.querySelector('[data-screen="library"]').click();assert.ok(d.querySelectorAll('.library-card').length>35);assert.ok(d.getElementById('screen-library').classList.contains('active'));
  const filter=d.getElementById('library-category');filter.value='Full body';filter.dispatchEvent(new w.Event('input'));assert.ok(d.querySelectorAll('.library-card').length>3);assert.ok([...d.querySelectorAll('.library-card small')].every(x=>x.textContent.startsWith('Full body')));
  d.querySelector('[data-screen="plan"]').click();d.getElementById('start-session').click();d.getElementById('skip-readiness').click();
  const row=d.querySelector('[data-ex="2"][data-set="0"]');row.querySelector('[data-key="weight"]').value='24';row.querySelector('[data-key="weight"]').dispatchEvent(new w.Event('input'));row.querySelector('.set-done').click();
  const before=JSON.parse(w.localStorage.getItem('oat5.active')),oldName=before.planSnapshot.exercises[2].name;
  d.querySelector('[data-replace="2"]').click();const search=d.getElementById('library-search');search.value='Lateral Lunge';search.dispatchEvent(new w.Event('input'));d.querySelector('.replace-choice').click();
  let a=JSON.parse(w.localStorage.getItem('oat5.active'));assert.match(a.planSnapshot.exercises[2].name,/Lateral Lunge/);assert.equal(a.planSnapshot.exercises[2].rest,before.planSnapshot.exercises[2].rest);assert.equal(a.replacedDetails[0].sets[0].weight,'24');assert.equal(a.replacedDetails[0].sets[0].done,true);assert.equal(a.replacements[0].from,oldName);
  dom.window.close();dom=boot({'oat5.active':a});w=dom.window;d=w.document;assert.match(d.getElementById('workout-content').textContent,/Lateral Lunge/);d.getElementById('finish-session').click();const h=JSON.parse(w.localStorage.getItem('oat5.history'))[0];assert.equal(h.details.find(ex=>ex.replaced).sets[0].weight,'24');assert.equal(h.completedSets,1);
  d.querySelector('[data-edit-session="'+h.id+'"]').click();d.getElementById('save-session-edit').click();assert.equal(JSON.parse(w.localStorage.getItem('oat5.history'))[0].replacements[0].from,oldName);dom.window.close();
});
test('cardio replacement keeps prescribed intervals and resets machine-specific logs',()=>{
  const dom=boot(),w=dom.window,d=w.document;d.getElementById('start-session').click();d.getElementById('skip-readiness').click();let a=JSON.parse(w.localStorage.getItem('oat5.active'));const index=a.planSnapshot.exercises.findIndex(ex=>ex.intervals),intervals=a.planSnapshot.exercises[index].intervals;
  d.querySelector('[data-replace="'+index+'"]').click();assert.ok([...d.querySelectorAll('.library-card small')].every(el=>el.textContent.startsWith('Cardio')));const search=d.getElementById('library-search');search.value='Rower';search.dispatchEvent(new w.Event('input'));d.querySelector('.replace-choice').click();a=JSON.parse(w.localStorage.getItem('oat5.active'));assert.equal(a.planSnapshot.exercises[index].machine,'Rower');assert.deepEqual(a.planSnapshot.exercises[index].intervals,intervals);assert.equal(a.sets.filter(s=>s.exerciseIndex===index).reduce((n,s)=>n+s.durationSec,0),1800);dom.window.close();
});
test('backup import merges without overwriting history and rejects malformed backup',async()=>{const seed={id:'existing',dayId:'day1',finishedAt:Date.now(),details:[]},dom=boot({'oat5.history':[seed]}),w=dom.window,input=w.document.getElementById('backup-file');const backup={history:[{...seed,details:[{name:'overwrite'}]},{id:'imported',dayId:'day2',finishedAt:1,details:[]}],knee:[],readiness:[],plans:[],goals:[],tests:[],weeklyReviews:[]};Object.defineProperty(input,'files',{configurable:true,value:[{text:async()=>JSON.stringify(backup)}]});input.dispatchEvent(new w.Event('change'));await new Promise(r=>setImmediate(r));let history=JSON.parse(w.localStorage.getItem('oat5.history'));assert.equal(history.length,2);assert.equal(history[0].details.length,0);assert.match(w.document.getElementById('import-status').textContent,/Còpia importada/);Object.defineProperty(input,'files',{configurable:true,value:[{text:async()=>'{"history":42}'}]});input.dispatchEvent(new w.Event('change'));await new Promise(r=>setImmediate(r));assert.equal(JSON.parse(w.localStorage.getItem('oat5.history')).length,2);assert.match(w.document.getElementById('import-status').textContent,/No s’ha importat/);dom.window.close();});
test('random cues run 10 times, persist direction counts, and can stop',()=>{const dom=boot(),w=dom.window,d=w.document;d.querySelector('[data-day="day3"]').click();d.getElementById('start-session').click();d.getElementById('skip-readiness').click();const callbacks=[];w.setTimeout=fn=>{callbacks.push(fn);return callbacks.length;};w.clearTimeout=()=>{};d.getElementById('reaction-start').click();for(let i=0;i<21;i++){const fn=callbacks.shift();assert.ok(fn);fn();}const a=JSON.parse(w.localStorage.getItem('oat5.active')),s=a.sets.find(s=>s.exerciseIndex===5&&s.setIndex===0);assert.equal(['Left','Right','Front','Back'].reduce((n,dir)=>n+s['cues'+dir],0),10);assert.equal(s.targetDistanceM,'1.0');assert.equal(s.arrivalWindowSec,'1.0');assert.equal(s.returnWindowSec,'2.0');assert.equal(s.done,false);assert.equal(d.getElementById('reaction-start').disabled,false);dom.window.close();});
function boot(seed={}){const dom=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'https://example.test/trials/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>true;w.scrollTo=()=>{};w.alert=msg=>{throw Error(msg)};Object.entries(seed).forEach(([k,v])=>w.localStorage.setItem(k,JSON.stringify(v)));w.eval(['legacy-data.js','data.js','v6.js','app.js'].map(p=>fs.readFileSync(root+'/'+p,'utf8')).join('\n'));return dom;}
test('four days and all cardio exactly 30 minutes',()=>{const c=vm.createContext({});vm.runInContext(fs.readFileSync(root+'/data.js','utf8'),c);const days=vm.runInContext('DAYS',c);assert.equal(days.length,4);days.forEach(d=>assert.equal(d.exercises.find(e=>e.intervals).intervals.reduce((n,s)=>n+s.durationSec,0),1800));assert.equal(days[1].exercises[0].sets,3);assert.equal(days[0].exercises[2].sets,4);});
test('weighted cardio averages, missing results and best/worst drop-off',()=>{const c=vm.createContext({});vm.runInContext(fs.readFileSync(root+'/v6.js','utf8'),c);const result=vm.runInContext(`V6.summary([{done:true,intervalType:'Hard',durationSec:60,distanceKm:'0.3'},{done:true,intervalType:'Hard',durationSec:60,distanceKm:'0.2'},{done:true,intervalType:'Chill',durationSec:120,distanceKm:'0.4'}],{machine:'Rower'})`,c);assert.equal(result.totalDistance,.9);assert.equal(result.averageHardSpeed,15);assert.equal(result.averageHardPace,120);assert.ok(Math.abs(result.dropOff-33.33333)<.001);assert.equal(vm.runInContext('V6.summary([],{machine:"Bike"}).dropOff',c),null);});
test('live interval → finish → calendar → edit retains metadata and arbitrary fields',()=>{const dom=boot(),w=dom.window,d=w.document;d.getElementById('start-session').click();d.getElementById('skip-readiness').click();const stored=()=>JSON.parse(w.localStorage.getItem('oat5.active'));assert.equal(stored().version,6);const row=d.querySelector('.interval-list .set-row');const input=row.querySelector('[data-key="distanceKm"]');input.value='.5';input.dispatchEvent(new w.Event('input',{bubbles:true}));row.querySelector('.set-done').click();const data=stored();const interval=data.sets.find(s=>s.intervalType==='Warm-up');assert.equal(interval.distanceKm,'.5');assert.equal(interval.durationSec,300);d.getElementById('finish-session').click();let history=JSON.parse(w.localStorage.getItem('oat5.history')),session=history[0];const cardio=session.details.find(e=>e.intervals);assert.equal(cardio.sets[0].durationSec,300);assert.equal(cardio.sets[0].distanceKm,'.5');d.querySelector('[data-view-session="'+session.id+'"]').click();assert.match(d.getElementById('calendar-sessions').textContent,/Hard average/);d.querySelector('[data-edit-session="'+session.id+'"]').click();d.getElementById('save-session-edit').click();history=JSON.parse(w.localStorage.getItem('oat5.history'));const edited=history.find(s=>s.id===session.id).details.find(e=>e.intervals);assert.equal(edited.machine,'Bike');assert.equal(edited.sets[0].durationSec,300);assert.equal(edited.sets[0].distanceKm,'.5');dom.window.close();});
test('legacy active session and history survive V6 boot',()=>{const old={id:'old-active',dayId:'day1',startedAt:Date.now(),sets:[{exerciseIndex:0,setIndex:0,weight:'11',repsDone:'10',done:true}]};const h={id:'past',dayId:'day2',finishedAt:Date.now(),durationSec:5400,details:[{name:'Nordic Hamstring',block:'GENOLL + CAMA',sets:[{done:true,repsDone:'6',customLegacy:'keep'}]}]};const dom=boot({'oat5.active':old,'oat5.history':[h],'oat5.oct3VideoImportedV1':true});const w=dom.window;assert.equal(JSON.parse(w.localStorage.getItem('oat5.active')).planSnapshot.exercises[0].name,'Leg Extension Unilateral');assert.equal(JSON.parse(w.localStorage.getItem('oat5.active')).sets[0].weight,'11');const d=w.document;d.querySelector('[data-edit-session="past"]').click();d.getElementById('save-session-edit').click();const preserved=JSON.parse(w.localStorage.getItem('oat5.history')).find(s=>s.id==='past');assert.equal(preserved.details[0].sets[0].customLegacy,'keep');dom.window.close();});
test('D3 reaction counters and plyo fields persist through history',()=>{const dom=boot(),w=dom.window,d=w.document;d.querySelector('[data-day="day3"]').click();d.getElementById('start-session').click();d.getElementById('skip-readiness').click();assert.ok(d.querySelector('[data-key="dropHeightCm"]'));assert.ok(d.querySelector('[data-key="jump1Cm"]'));const row=d.querySelector('[data-key="cuesLeft"]').closest('.set-row');[['cuesLeft','4'],['cuesRight','6'],['correctLeft','3'],['onTimeLeft','2']].forEach(([key,value])=>{const input=row.querySelector('[data-key="'+key+'"]');input.value=value;input.dispatchEvent(new w.Event('input',{bubbles:true}));});row.querySelector('.set-done').click();assert.match(d.querySelector('[data-summary-ex="5"]').textContent,/50.00%/);d.getElementById('finish-session').click();assert.equal(JSON.parse(w.localStorage.getItem('oat5.history'))[0].details[5].sets[0].onTimeLeft,'2');dom.window.close();});

